= Piano

== Intro

I'm learning piano and I'm using this space to document my progress. +  
It's also a place where I can organize all my home-made musical scores. +  
For the creation of the musical scores, I use the following open source applications: +  

* link:http://www.lilypond.org[lilypond] +  
* link:http://www.frescobaldi.org/index.html[frescobaldi] +  

The first application is for creating the musical scores, the second one is a graphical editor,
that makes working with the scores easier.

== 2017-05-18

Learnt how to use lilypond, by using their tutorials. The result is link:assets/score_20170518_V001_MyFirstScore.pdf[here]. +  
Don't know how to play it though. It was just created to learn to use lilypond.

== 2017-05-21

Getting ready to learn to play left and right handed. I created a nice score for learning left and right handed playing. +  
You can find it link:assets/score_20170521_V001_PracticeLeftRight.pdf[here].

== 2017-05-27

I've been studying in the books I have bought: +  
* Faber - All-in-one - Adult piano adventures 1
* Faber - All-in-one - Adult piano adventures 2

The instrument I'm using is a Yamaha DGX-660. +  

The books are nice. Most of it seems easy enough though, because I've already studied some musical notation through the internet. +  
But I keep doing all the exercises and I follow every lesson. I'm serious about this.

== 2017-06-02

I already did 45 pages of the first book. The pieces are getting more into playing with both hands. It's getting interesting.
