= The Religion Of Equilibrium

== General info

This webpage contains information about a religion, called: +  
**The Religion Of Equilibrium**.

== Important terminology

* The religion is called *The Religion Of Equilibrium*. No other name is valid.
* Followers of this religion, are called *followers of The Religion Of Equilibrium*. No other name is valid. This religion is all about being as neutral as possible, and long and boring names prevent mis-use of certain terminology linked to this religion. See the rules for more information.

== Rules

=== 1 You must strive for balance and neutrality in all that you do

You must try to be as neutral as possible.
Too much is not a good thing.
Too little is not a good thing.
Nobody can be good all the time, just as nobody can be bad all the time. Try to be as neutral as possible. If you do something good, that is fine. But know you can not keep doing this all the time.
If you do something bad, accept and understand what you did. Mistakes happen and it is the next thing you are going to do, that is the most important.

=== 2 No deity is a part of this religion.

It's fine to believe in a deity, but that is not part of this religion. Also note, that neutrality is an important concept. Another belief can not force you into a radical direction. That would violate rule number 1.

=== 3 No symbol can represent this religion.

A symbol can be used to show your passion for something. But that could also lead to its use in obsessions and negative or commercial actions. This could cause violations of rule number 1.


